
project_id = "ixoqqggstwmezrmkyvuu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[cdn]
enabled = false

[functions.create-drive-folders]
verify_jwt = true

[functions.create-client-user]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.list-drive-folders]
verify_jwt = true

[realtime]
enabled = true
