// This file is automatically generated. Do not edit it directly.
import type { Database } from "./types";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
