// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixoqqggstwmezrmkyvuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4b3FxZ2dzdHdtZXpybWt5dnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjI4NTIsImV4cCI6MjA2MzM5ODg1Mn0.NzhQcmgHYHRL6e4igWKmB8hzAjp-rBoYvL-Wi1Tk5ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);